name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - ipywidgets
  - bqplot
  - geopandas
  - requests
  - pip:
    - pillow
    - bqplot
    - geopandas
    - requests
    - descartes